version: "3.1"
services:   
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./api:/src/api
      - ./api_tests:/src/api_tests
      - ./alembic.ini:/src/alembic.ini
      - ./docker/uwsgi/uwsgi.ini:/src/uwsgi.ini
    env_file: 
      - .env
    expose:
      - 5000
    depends_on:
      - db
    command: uwsgi --ini uwsgi.ini --py-autoreload 1

  db:
    image: postgres:10-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
