"""add comments

Revision ID: 2e27530f864e
Revises: 0c5f9b953a78
Create Date: 2019-05-01 15:01:33.771500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e27530f864e'
down_revision = '0c5f9b953a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('id_manga', sa.Integer(), nullable=True),
    sa.Column('id_chapter', sa.Integer(), nullable=True),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_chapter'], ['chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_manga'], ['manga.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
