"""add manga created

Revision ID: 58d4f8b9a119
Revises: 3fcc72c01fe4
Create Date: 2019-03-12 18:30:33.192314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d4f8b9a119'
down_revision = '3fcc72c01fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('created', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga', 'created')
    # ### end Alembic commands ###
